name: 🐞 Submit a bug report
description: Facing errors or unexpected behavior?
type: bug

body:

- type: markdown
  attributes:
    value: <div align="center"><h2>📦 Basic Information 📦</h2></div>

- type: dropdown
  id: operating-system
  attributes:
    label: Operating system
    description: |
      - Where are you experiencing the problem?
    options:
      - 💠 Windows 11
      - 💠 Windows 10
      - 🍎 macOS (Apple Silicon)
      - 🍎 macOS (Intel)
      - 🐧 Linux (Ubuntu-like)
      - 🐧 Linux (Fedora-like)
      - 🐧 Linux (Arch-like)
      - 🐧 Linux (Specify)
      - Others (Specify)
      - N/A
    multiple: true
    default: 0
  validations:
    required: true

- type: dropdown
  id: runtime-method
  attributes:
    label: Runtime method
    description: |
      - Where are you running the projects from?
    options:
      - 📦 PyApp executables
      - 🧀 PyPI wheels (pip)
      - 🔥 Source code (git main)
      - 🐳 Docker containers
      - 🦭 Podman containers
      - ☁️ Cloud services
      - N/A
    multiple: true
    default: 0
  validations:
    required: true

- type: input
  id: project-version
  attributes:
    label: Project version
    description: |
      - **Check** the file name, console logs, or run `project --version`
      - **Examples**: 0.9.0, latest, 0.8.0.dev0, etc.
  validations:
    required: false

- type: dropdown
  id: python-version
  attributes:
    label: Python version
    description: |
      - **📦 Executables**: Keep the default (Auto-managed) option
      - **🧀 PyPI Wheels**: Check the Python version with `python --version`
      - **🔥 Source Code**: Keep (Auto-managed) or find in `.python-version` file
    options:
      - Auto-managed
      - Python 3.9
      - Python 3.10
      - Python 3.11
      - Python 3.12
      - Python 3.13
      - Python 3.13t
      - Python 3.14
      - Python 3.14t
      - N/A
    default: 0
  validations:
    required: true

- type: dropdown
  id: gpu-vendor
  attributes:
    label: GPU Brand
    description: |
      - **Select all that apply**; Feel free to leave it blank if the issue/project isn't GPU related
      - **Hybrid systems:** See in logs the GPU being used, switch on your OS if wrong one
    options:
      - 🟢 NVIDIA Desktop
      - 🟢 NVIDIA Laptop
      - 🔴 AMD Desktop
      - 🔴 AMD Laptop
      - 🔵 Intel Desktop
      - 🔵 Intel Laptop
      - 🍎 Apple Silicon
    multiple: true
  validations:
    required: false

- type: input
  id: gpu-model
  attributes:
    label: GPU Model
    description: |
      - **If applicable**, provide the model of the GPU(s) you're using
      - **Examples**: RTX 3090, RX 6800 XT, Arc B580, Iris Xe, etc.
      - **🍎 Apple Silicon**: Leave this field blank
  validations:
    required: false

- type: markdown
  attributes:
    value: <div align="center"><h2>🔥 Report Details 🔥</h2></div>

- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      - ✅ Report which parts of the code or features are failing, or your best guess of what went wrong
      - ✅ If you have anything to contribute, like a workaround or fix, feel free to share them too!
      - **Tip:** You can provide a Python script, commands, links, steps to reproduce the issue
      - **Tip:** You can <kbd>CTRL+V</kbd> screenshots, videos, to help explain the issue
  validations:
    required: true

- type: textarea
  id: traceback
  attributes:
    label: Traceback
    description: |
      - **If relevant**, paste the full traceback, error message, or log file here
      - **Tip:** You can use [**GitHub Gists**](https://gist.github.com/) to share multiple files
    render: shell
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      ###### © CC-BY-4.0, Issue Template by [**Tremeschin**](https://github.com/Tremeschin) 🇧🇷
