name: 💡 Share your thoughts
description: Got suggestions to improve the project?
type: feature

body:

- type: markdown
  attributes:
    value: <div align="center"><h2>🔥 Feedback Details 🔥</h2></div>

- type: dropdown
  id: report-type
  attributes:
    label: Report type
    description: |
      - What kind of feedback are you providing?
    options:
      - General feedback
      - New functionality
      - User experience
      - Documentation
      - Enhancement
      - Integration
      - Others (specify)
    default: 0
  validations:
    required: true

- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      - ✅ Describe the feature you'd like to see implemented or feedback to be heard
      - **Tip:** You can provide a Python script, commands, of how the feature would work
      - **Tip:** You can <kbd>CTRL+V</kbd> Screenshots, Videos, to provide examples or mockups
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ###### © CC-BY-4.0, Issue Template by [**Tremeschin**](https://github.com/Tremeschin) 🇧🇷
