name: 🤔 Ask a question
description: Need quick help or insights?

body:

- type: markdown
  attributes:
    value: <div align="center"><h2>🔥 Question Details 🔥</h2></div>

- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      - ✅ Describe the question you need help with
      - **Tip:** Add any relevant context, error logs, or code examples
      - **Tip:** You can include screenshots or videos for better clarity
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ###### © CC-BY-4.0, Issue Template by [**Tremeschin**](https://github.com/Tremeschin) 🇧🇷
