name: â“ Create a new question ticket
description: Have a question about the project?

body:
- type: markdown
  attributes:
    value: |
      > [!IMPORTANT]
      > - âš ï¸ Please use the Discussions tab above for questions!
      > - You can also ask your question on [**Discord or Telegram**](https://brokensrc.dev/about/contact/)

- type: dropdown
  attributes:
    label: "Please read the message above!"
    options:
      - Ok!
    default: 0

- type: markdown
  attributes:
    value: |
      ###### Â© CC-BY-4.0, Issue Template by [**Tremeschin**](https://github.com/Tremeschin) ðŸ‡§ðŸ‡·
