name: make-pypi
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - run:  uv build --wheel
      - run:  uv publish
